import { useEffect, useState } from "react";
import { jsPDF } from "jspdf";
import "./Stage2.css";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";

const apiBaseUrl = import.meta.env.VITE_API_BASE_URL ?? "https://backend-startup-6qlv.onrender.com";

type ApplicationPayload = {
  idea: string;
  leader: string;
  email: string;
  phone: string;
  department: string;
  teams: string[];
  track: string;
  sector: string;
  description: string;
};

const createApplicationPdf = (application: ApplicationPayload) => {
  const pdf = new jsPDF({ unit: "mm", format: "a4" });

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text("STARTUP APPLICATION", 105, 20, { align: "center" });

  pdf.setDrawColor(41, 128, 185);
  pdf.setLineWidth(1);
  pdf.line(15, 24, 195, 24);

  const textSection = (label: string, value: string, yStart: number) => {
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text(label, 15, yStart);
    pdf.setFont("helvetica", "normal");
    pdf.text(value, 15, yStart + 6, { maxWidth: 180 });
  };

  let currentY = 34;

  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("Applicant Details", 15, currentY);
  currentY += 8;

  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");
  textSection("Venture / Idea name:", application.idea, currentY);
  currentY += 10;
  textSection("Team leader:", application.leader, currentY);
  currentY += 10;
  textSection("Email:", application.email, currentY);
  currentY += 10;
  textSection("Phone:", application.phone, currentY);
  currentY += 10;
  textSection("Department:", application.department, currentY);
  currentY += 14;

  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("Startup Details", 15, currentY);
  currentY += 8;

  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");
  textSection("Track:", application.track, currentY);
  currentY += 10;

  textSection("Sector:", application.sector, currentY);
  currentY += 10;

  // Description
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.text("Description:", 15, currentY);

  currentY += 7;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);

  const descriptionLines = pdf.splitTextToSize(
    application.description,
    180
  );

  descriptionLines.forEach((line: string) => {
    // Create a new page if there isn't enough space
    if (currentY > 270) {
      pdf.addPage();
      currentY = 20;
    }

    pdf.text(line, 15, currentY);
    currentY += 6;
  });

  currentY += 8;

  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("Team Members", 15, currentY);
  currentY += 8;

  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");

  application.teams.forEach((member, index) => {
    if (currentY > 270) {
      pdf.addPage();
      currentY = 20;
    }

    pdf.text(`${index + 1}. ${member}`, 18, currentY);
    currentY += 8;
  });
  if (currentY > 270) {
    pdf.addPage();
    currentY = 20;
  }

  pdf.setFontSize(10);
  pdf.setTextColor(120, 120, 120);
  pdf.text("Generated by Startup Application Portal", 105, 287, { align: "center" });

  return pdf.output("blob");
};

const Stage2 = () => {
  const [track, setTrack] = useState("");
  const [sector, setSector] = useState("");
  const [otherSector, setOtherSector] = useState("");
  const [description, setDescription] = useState("");
  const [loading, setLoading] = useState(false);
  const [dis, setDis] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    const savedStage1 = localStorage.getItem("stage1");
    if (!savedStage1) {
      navigate("/");
    }
  }, [navigate]);

  const handleSumbit = async () => {
    const descriptionWordCount = description.trim().split(/\s+/).filter(Boolean).length;

    if (!track) {
      toast.error("Please select a track.");
      return;
    }

    if (!sector) {
      toast.error("Please select a sector.");
      return;
    }

    if (sector === "Other" && !otherSector.trim()) {
      toast.error("Please enter your sector.");
      return;
    }

    if (descriptionWordCount === 0) {
      toast.error("Please enter a startup description.");
      return;
    }

    if (descriptionWordCount > 150) {
      toast.error("Keep the startup description to 150 words or fewer.");
      return;
    }

    let stage1: Record<string, unknown>;
    try {
      stage1 = JSON.parse(localStorage.getItem("stage1") || "{}");
    } catch {
      toast.error("Your form session is invalid. Please fill Stage 1 again.");
      navigate("/");
      return;
    }

    const idea = typeof stage1.idea === "string" ? stage1.idea.trim() : "";
    const leader = typeof stage1.leader === "string" ? stage1.leader.trim() : "";
    const email = typeof stage1.email === "string" ? stage1.email.trim() : "";
    const phone = typeof stage1.phone === "string" ? stage1.phone.trim() : "";
    const department = typeof stage1.department === "string" ? stage1.department.trim() : "";
    const teams = Array.isArray(stage1.teams) ? stage1.teams.filter((t): t is string => typeof t === "string").map((t) => t.trim()) : [];

    if (!idea || !leader || !email || !phone || !department || teams.length === 0) {
      toast.error("Please complete Stage 1 before submitting.");
      navigate("/");
      return;
    }

    const application: ApplicationPayload = {
      idea,
      leader,
      email,
      phone,
      department,
      teams,
      track,
      sector: sector === "Other" ? otherSector : sector,
      description: description.trim(),
    };

    setLoading(true);
    setDis(true);

    // Parse the (possibly) unstructured description text and produce
    // a mapping from existing fields -> array of original description strings.
    const parseDescriptions = (text: string): Record<string, string[]> => {
      const snippets = text
        .split(/\n{2,}|\r\n{2,}/) // split on double newlines
        .map((s) => s.trim())
        .filter(Boolean);

      const mapping: Record<string, string[]> = {};
      const push = (key: string, val: string) => {
        if (!mapping[key]) mapping[key] = [];
        mapping[key].push(val);
      };

      const trackKeywords = [
        "Technology",
        "Sustainability",
        "Social",
        "FinTech",
        "HealthTech",
        "EdTech",
        "Consumer",
        "AgriTech",
        "Open Innovation",
      ];

      const sectorKeywords = [
        "Healthcare",
        "Education",
        "Agriculture",
        "E-commerce",
        "Finance",
        "Climate",
        "Artificial Intelligence",
        "Manufacturing",
        "Transportation",
        "Media",
        "Food",
        "Travel",
      ];

      const emailRegex = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i;
      const phoneRegex = /(?:\+?\d[\d\s().-]{5,}\d)/;

      for (const s of snippets) {
        // preserve original snippet exactly
        const original = s;

        // strong signals first
        if (emailRegex.test(s)) {
          push("email", original);
          continue;
        }

        if (phoneRegex.test(s)) {
          push("phone", original);
          continue;
        }

        // check for team lists (commas or lines of names)
        if (/\bteam\b/i.test(s) || /,/.test(s) && s.split(",").length >= 2) {
          push("teams", original);
          continue;
        }

        // leader name heuristics (short phrase with capitalized words)
        if (/^([A-Z][a-z]+\s?){1,3}$/.test(s)) {
          push("leader", original);
          continue;
        }

        // track keywords
        if (trackKeywords.some((k) => new RegExp(k, "i").test(s))) {
          push("track", original);
          continue;
        }

        // sector keywords
        if (sectorKeywords.some((k) => new RegExp(k, "i").test(s))) {
          push("sector", original);
          continue;
        }

        // short idea-like phrases
        if (s.length < 80 && /\b(app|platform|service|product|solution|system)\b/i.test(s)) {
          push("idea", original);
          continue;
        }

        // default: consider it a description candidate
        // but if we cannot confidently map, place under Unassigned
        // We'll use a conservative approach: place into `description` if it contains problem/impact keywords
        if (/\b(problem|solve|impact|market|users|customers|benefit|reduce|improve)\b/i.test(s)) {
          push("description", original);
          continue;
        }

        // fallback
        push("Unassigned", original);
      }

      return mapping;
    };

    const parsed = parseDescriptions(application.description);

    try {
      const pdfBlob = createApplicationPdf(application);
      const formData = new FormData();

      formData.append("idea", application.idea);
      formData.append("leader", application.leader);
      formData.append("email", application.email);
      formData.append("phone", application.phone);
      formData.append("department", application.department);
      formData.append("track", application.track);
      formData.append("sector", application.sector);
      formData.append("description", application.description);
      // Attach parsed descriptions JSON as an optional field. We do not
      // change existing field names; this is an additional optional payload
      // that the backend will ingest if present.
      try {
        formData.append("parsedDescriptions", JSON.stringify(parsed));
      } catch (e) {
        console.error("failed to attach parsedDescriptions", e);
      }

      application.teams.forEach((team) => formData.append("teams", team));
      formData.append("applicationPDF", new File([pdfBlob], "startup_application.pdf", { type: "application/pdf" }));

      const res = await fetch(`${apiBaseUrl}/application`, {
        method: "POST",
        body: formData,
      });

      const data = await res.json().catch(() => ({}));

      if (res.ok && data && data.success === true) {
        toast.success("Application submitted successfully and saved to Google Drive.");
        navigate("/submit");
      } else {
        const msg = (data && data.message) || `Application submission failed${res.status ? ` (status ${res.status})` : ""}`;
        toast.error(msg);
        return;
      }
    } catch (error) {
      console.error("SUBMIT ERROR:", error);
      toast.error("Unable to connect to server. Please try again.");
    } finally {
      setLoading(false);
      setDis(false);
    }
  };

  return (
    <div className="stage2-container">
      <div className="stage2-hero">
        <div>
          <p className="stage2-eyebrow">Step 2 of 2</p>
          <h2 className="stage-title">Startup Details</h2>
        </div>
        <div className="stage2-badge">Secure submission</div>
      </div>

      <div className="stage2-group">
        <label className="stage2-label">Track (Board)</label>

        <select
          className="stage2-select"
          value={track}
          onChange={(e) => setTrack(e.target.value)}
        >
          <option value="">Select Track</option>
          <option value="Technology & Innovation">Technology & Innovation</option>
          <option value="Sustainability & CleanTech">Sustainability & CleanTech</option>
          <option value="Social Impact">Social Impact</option>
          <option value="FinTech">FinTech</option>
          <option value="HealthTech">HealthTech</option>
          <option value="EdTech">EdTech</option>
          <option value="Consumer & D2C">Consumer & D2C</option>
          <option value="AgriTech">AgriTech</option>
          <option value="Open Innovation">Open Innovation</option>
        </select>
      </div>

      <div className="stage2-group">
        <label className="stage2-label">Sector</label>

        <select
          className="stage2-select"
          value={sector}
          onChange={(e) => setSector(e.target.value)}
        >
          <option value="">Select Sector</option>
          <option value="Healthcare">Healthcare</option>
          <option value="Education">Education</option>
          <option value="Agriculture">Agriculture</option>
          <option value="E-commerce / Retail">E-commerce / Retail</option>
          <option value="Finance & Banking">Finance & Banking</option>
          <option value="Climate & Environment">Climate & Environment</option>
          <option value="Artificial Intelligence / Deep Tech">Artificial Intelligence / Deep Tech</option>
          <option value="Manufacturing">Manufacturing</option>
          <option value="Transportation & Logistics">Transportation & Logistics</option>
          <option value="Media & Entertainment">Media & Entertainment</option>
          <option value="Food & Beverage">Food & Beverage</option>
          <option value="Travel & Hospitality">Travel & Hospitality</option>
          <option value="Other">Other</option>
        </select>

        {sector === "Other" && (
          <input
            className="stage2-input"
            type="text"
            placeholder="Enter your sector"
            value={otherSector}
            onChange={(e) => setOtherSector(e.target.value)}
          />
        )}
      </div>

      <div className="stage2-group">
        <label className="stage2-label" htmlFor="description">Startup description (up to 150 words)</label>
        <textarea
          id="description"
          className="stage2-input stage2-textarea"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Describe your startup idea, the problem it solves, and its impact."
          rows={7}
        />
        <span className="word-count">{description.trim().split(/\s+/).filter(Boolean).length} / 150 words</span>
      </div>

      <div className="stage2-buttons">
        <button className="back-btn" onClick={() => navigate("/")}>Back</button>
        <button disabled={dis} className="next-btn" onClick={handleSumbit}>{loading ? "Submitting..." : "Submit"}</button>
      </div>

    </div>
  );
};

export default Stage2;
