import { useEffect, useState } from "react";
import { jsPDF } from "jspdf";
import "./Stage2.css";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";

const apiBaseUrl = import.meta.env.VITE_API_BASE_URL ?? "https://backend-startup-6qlv.onrender.com";

type ApplicationPayload = {
  idea: string;
  leader: string;
  email: string;
  phone: string;
  department: string;
  teams: string[];
  track: string;
  sector: string;
  description: string;
};
const createApplicationPdf = (application: ApplicationPayload) => {
  const pdf = new jsPDF({ unit: "mm", format: "a4" });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  const bottomMargin = 22;

  let currentY = 35;

  // -----------------------------
  // PAGE BREAK
  // -----------------------------
  const checkPageBreak = (requiredSpace = 10) => {
    if (currentY + requiredSpace > pageHeight - bottomMargin) {
      pdf.addPage();
      currentY = 25;
    }
  };

  // -----------------------------
  // HEADER
  // -----------------------------
  const drawHeader = () => {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(20);
    pdf.setTextColor(25, 25, 25);

    pdf.text(
      "STARTUP APPLICATION",
      pageWidth / 2,
      18,
      { align: "center" }
    );

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(100, 100, 100);

    pdf.text(
      "Startup Application Portal",
      pageWidth / 2,
      24,
      { align: "center" }
    );

    pdf.setDrawColor(41, 128, 185);
    pdf.setLineWidth(0.8);
    pdf.line(margin, 29, pageWidth - margin, 29);
  };

  // Draw header on first page
  drawHeader();

  // -----------------------------
  // FOOTER
  // -----------------------------
  const addFooter = () => {
    const pageCount = pdf.getNumberOfPages();

    for (let page = 1; page <= pageCount; page++) {
      pdf.setPage(page);

      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(8);
      pdf.setTextColor(120, 120, 120);

      pdf.line(
        margin,
        pageHeight - 16,
        pageWidth - margin,
        pageHeight - 16
      );

      pdf.text(
        "Generated by Startup Application Portal",
        margin,
        pageHeight - 10
      );

      pdf.text(
        `Page ${page} of ${pageCount}`,
        pageWidth - margin,
        pageHeight - 10,
        { align: "right" }
      );
    }
  };

  // -----------------------------
  // SECTION HEADER
  // -----------------------------
  const sectionTitle = (title: string) => {
    checkPageBreak(18);

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(13);
    pdf.setTextColor(41, 128, 185);

    pdf.text(title.toUpperCase(), margin, currentY);

    pdf.setDrawColor(210, 210, 210);
    pdf.setLineWidth(0.4);

    pdf.line(
      margin,
      currentY + 3,
      pageWidth - margin,
      currentY + 3
    );

    currentY += 11;
  };

  // -----------------------------
  // LABEL + VALUE
  // -----------------------------
  const field = (label: string, value: string) => {
    checkPageBreak(10);

    const labelWidth = 45;

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(10);
    pdf.setTextColor(60, 60, 60);

    pdf.text(label, margin, currentY);

    const valueLines = pdf.splitTextToSize(
      value || "-",
      contentWidth - labelWidth
    );

    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(20, 20, 20);

    pdf.text(
      valueLines,
      margin + labelWidth,
      currentY
    );

    currentY += Math.max(7, valueLines.length * 5.5);

    currentY += 2;
  };

  // -----------------------------
  // APPLICANT DETAILS
  // -----------------------------
  sectionTitle("Applicant Details");

  field("Venture / Idea:", application.idea);
  field("Team Leader:", application.leader);
  field("Email:", application.email);
  field("Phone:", application.phone);
  field("Department:", application.department);

  currentY += 5;

  // -----------------------------
  // STARTUP DETAILS
  // -----------------------------
  sectionTitle("Startup Details");

  field("Track:", application.track);
  field("Sector:", application.sector);

  currentY += 4;

  // -----------------------------
  // DESCRIPTION
  // -----------------------------
  checkPageBreak(20);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(11);
  pdf.setTextColor(60, 60, 60);

  pdf.text("DESCRIPTION", margin, currentY);

  currentY += 8;

  const descriptionLines = pdf.splitTextToSize(
    application.description || "-",
    contentWidth
  );

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10.5);
  pdf.setTextColor(25, 25, 25);

  descriptionLines.forEach((line: string) => {
    checkPageBreak(6);

    pdf.text(line, margin, currentY);

    currentY += 5.5;
  });

  currentY += 8;

  // -----------------------------
  // TEAM MEMBERS
  // -----------------------------
  sectionTitle("Team Members");

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10.5);
  pdf.setTextColor(25, 25, 25);

  application.teams.forEach((member, index) => {
    checkPageBreak(8);

    pdf.text(
      `${index + 1}.`,
      margin + 2,
      currentY
    );

    const memberLines = pdf.splitTextToSize(
      member,
      contentWidth - 10
    );

    pdf.text(
      memberLines,
      margin + 9,
      currentY
    );

    currentY += Math.max(
      6,
      memberLines.length * 5.5
    );

    currentY += 2;
  });

  // -----------------------------
  // FOOTER
  // -----------------------------
  addFooter();

  return pdf.output("blob");
};

const Stage2 = () => {
  const [track, setTrack] = useState("");
  const [sector, setSector] = useState("");
  const [otherSector, setOtherSector] = useState("");
  const [description, setDescription] = useState("");
  const [loading, setLoading] = useState(false);
  const [dis, setDis] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    const savedStage1 = localStorage.getItem("stage1");
    if (!savedStage1) {
      navigate("/");
    }
  }, [navigate]);

  const handleSumbit = async () => {
    const descriptionWordCount = description.trim().split(/\s+/).filter(Boolean).length;

    if (!track) {
      toast.error("Please select a track.");
      return;
    }

    if (!sector) {
      toast.error("Please select a sector.");
      return;
    }

    if (sector === "Other" && !otherSector.trim()) {
      toast.error("Please enter your sector.");
      return;
    }

    if (descriptionWordCount === 0) {
      toast.error("Please enter a startup description.");
      return;
    }

    if (descriptionWordCount > 150) {
      toast.error("Keep the startup description to 150 words or fewer.");
      return;
    }

    let stage1: Record<string, unknown>;
    try {
      stage1 = JSON.parse(localStorage.getItem("stage1") || "{}");
    } catch {
      toast.error("Your form session is invalid. Please fill Stage 1 again.");
      navigate("/");
      return;
    }

    const idea = typeof stage1.idea === "string" ? stage1.idea.trim() : "";
    const leader = typeof stage1.leader === "string" ? stage1.leader.trim() : "";
    const email = typeof stage1.email === "string" ? stage1.email.trim() : "";
    const phone = typeof stage1.phone === "string" ? stage1.phone.trim() : "";
    const department = typeof stage1.department === "string" ? stage1.department.trim() : "";
    const teams = Array.isArray(stage1.teams) ? stage1.teams.filter((t): t is string => typeof t === "string").map((t) => t.trim()) : [];

    if (!idea || !leader || !email || !phone || !department || teams.length === 0) {
      toast.error("Please complete Stage 1 before submitting.");
      navigate("/");
      return;
    }

    const application: ApplicationPayload = {
      idea,
      leader,
      email,
      phone,
      department,
      teams,
      track,
      sector: sector === "Other" ? otherSector : sector,
      description: description.trim(),
    };

    setLoading(true);
    setDis(true);

    // Parse the (possibly) unstructured description text and produce
    // a mapping from existing fields -> array of original description strings.
    const parseDescriptions = (text: string): Record<string, string[]> => {
      const snippets = text
        .split(/\n{2,}|\r\n{2,}/) // split on double newlines
        .map((s) => s.trim())
        .filter(Boolean);

      const mapping: Record<string, string[]> = {};
      const push = (key: string, val: string) => {
        if (!mapping[key]) mapping[key] = [];
        mapping[key].push(val);
      };

      const trackKeywords = [
        "Technology",
        "Sustainability",
        "Social",
        "FinTech",
        "HealthTech",
        "EdTech",
        "Consumer",
        "AgriTech",
        "Open Innovation",
      ];

      const sectorKeywords = [
        "Healthcare",
        "Education",
        "Agriculture",
        "E-commerce",
        "Finance",
        "Climate",
        "Artificial Intelligence",
        "Manufacturing",
        "Transportation",
        "Media",
        "Food",
        "Travel",
      ];

      const emailRegex = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i;
      const phoneRegex = /(?:\+?\d[\d\s().-]{5,}\d)/;

      for (const s of snippets) {
        // preserve original snippet exactly
        const original = s;

        // strong signals first
        if (emailRegex.test(s)) {
          push("email", original);
          continue;
        }

        if (phoneRegex.test(s)) {
          push("phone", original);
          continue;
        }

        // check for team lists (commas or lines of names)
        if (/\bteam\b/i.test(s) || /,/.test(s) && s.split(",").length >= 2) {
          push("teams", original);
          continue;
        }

        // leader name heuristics (short phrase with capitalized words)
        if (/^([A-Z][a-z]+\s?){1,3}$/.test(s)) {
          push("leader", original);
          continue;
        }

        // track keywords
        if (trackKeywords.some((k) => new RegExp(k, "i").test(s))) {
          push("track", original);
          continue;
        }

        // sector keywords
        if (sectorKeywords.some((k) => new RegExp(k, "i").test(s))) {
          push("sector", original);
          continue;
        }

        // short idea-like phrases
        if (s.length < 80 && /\b(app|platform|service|product|solution|system)\b/i.test(s)) {
          push("idea", original);
          continue;
        }

        // default: consider it a description candidate
        // but if we cannot confidently map, place under Unassigned
        // We'll use a conservative approach: place into `description` if it contains problem/impact keywords
        if (/\b(problem|solve|impact|market|users|customers|benefit|reduce|improve)\b/i.test(s)) {
          push("description", original);
          continue;
        }

        // fallback
        push("Unassigned", original);
      }

      return mapping;
    };

    const parsed = parseDescriptions(application.description);

    try {
      const pdfBlob = createApplicationPdf(application);
      const formData = new FormData();

      formData.append("idea", application.idea);
      formData.append("leader", application.leader);
      formData.append("email", application.email);
      formData.append("phone", application.phone);
      formData.append("department", application.department);
      formData.append("track", application.track);
      formData.append("sector", application.sector);
      formData.append("description", application.description);
      // Attach parsed descriptions JSON as an optional field. We do not
      // change existing field names; this is an additional optional payload
      // that the backend will ingest if present.
      try {
        formData.append("parsedDescriptions", JSON.stringify(parsed));
      } catch (e) {
        console.error("failed to attach parsedDescriptions", e);
      }

      application.teams.forEach((team) => formData.append("teams", team));
      formData.append("applicationPDF", new File([pdfBlob], "startup_application.pdf", { type: "application/pdf" }));

      const res = await fetch(`${apiBaseUrl}/application`, {
        method: "POST",
        body: formData,
      });

      const data = await res.json().catch(() => ({}));

      if (res.ok && data && data.success === true) {
        toast.success("Application submitted successfully and saved to Google Drive.");
        navigate("/submit");
      } else {
        const msg = (data && data.message) || `Application submission failed${res.status ? ` (status ${res.status})` : ""}`;
        toast.error(msg);
        return;
      }
    } catch (error) {
      console.error("SUBMIT ERROR:", error);
      toast.error("Unable to connect to server. Please try again.");
    } finally {
      setLoading(false);
      setDis(false);
    }
  };

  return (
    <div className="stage2-container">
      <div className="stage2-hero">
        <div>
          <p className="stage2-eyebrow">Step 2 of 2</p>
          <h2 className="stage-title">Startup Details</h2>
        </div>
        <div className="stage2-badge">Secure submission</div>
      </div>

      <div className="stage2-group">
        <label className="stage2-label">Track (Board)</label>

        <select
          className="stage2-select"
          value={track}
          onChange={(e) => setTrack(e.target.value)}
        >
          <option value="">Select Track</option>
          <option value="Technology & Innovation">Technology & Innovation</option>
          <option value="Sustainability & CleanTech">Sustainability & CleanTech</option>
          <option value="Social Impact">Social Impact</option>
          <option value="FinTech">FinTech</option>
          <option value="HealthTech">HealthTech</option>
          <option value="EdTech">EdTech</option>
          <option value="Consumer & D2C">Consumer & D2C</option>
          <option value="AgriTech">AgriTech</option>
          <option value="Open Innovation">Open Innovation</option>
        </select>
      </div>

      <div className="stage2-group">
        <label className="stage2-label">Sector</label>

        <select
          className="stage2-select"
          value={sector}
          onChange={(e) => setSector(e.target.value)}
        >
          <option value="">Select Sector</option>
          <option value="Healthcare">Healthcare</option>
          <option value="Education">Education</option>
          <option value="Agriculture">Agriculture</option>
          <option value="E-commerce / Retail">E-commerce / Retail</option>
          <option value="Finance & Banking">Finance & Banking</option>
          <option value="Climate & Environment">Climate & Environment</option>
          <option value="Artificial Intelligence / Deep Tech">Artificial Intelligence / Deep Tech</option>
          <option value="Manufacturing">Manufacturing</option>
          <option value="Transportation & Logistics">Transportation & Logistics</option>
          <option value="Media & Entertainment">Media & Entertainment</option>
          <option value="Food & Beverage">Food & Beverage</option>
          <option value="Travel & Hospitality">Travel & Hospitality</option>
          <option value="Other">Other</option>
        </select>

        {sector === "Other" && (
          <input
            className="stage2-input"
            type="text"
            placeholder="Enter your sector"
            value={otherSector}
            onChange={(e) => setOtherSector(e.target.value)}
          />
        )}
      </div>

      <div className="stage2-group">
        <label className="stage2-label" htmlFor="description">Startup description (up to 150 words)</label>
        <textarea
          id="description"
          className="stage2-input stage2-textarea"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Describe your startup idea, the problem it solves, and its impact."
          rows={7}
        />
        <span className="word-count">{description.trim().split(/\s+/).filter(Boolean).length} / 150 words</span>
      </div>

      <div className="stage2-buttons">
        <button className="back-btn" onClick={() => navigate("/")}>Back</button>
        <button disabled={dis} className="next-btn" onClick={handleSumbit}>{loading ? "Submitting..." : "Submit"}</button>
      </div>

    </div>
  );
};

export default Stage2;
