import { useEffect, useState } from "react";
import { jsPDF } from "jspdf";
import "./Stage2.css";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";

const apiBaseUrl = import.meta.env.VITE_API_BASE_URL ?? "https://backend-startup-6qlv.onrender.com";

type ApplicationPayload = {
  idea: string;
  leader: string;
  email: string;
  phone: string;
  department: string;
  teams: string[];
  track: string;
  sector: string;
  description: string;
};
const createApplicationPdf = (application: ApplicationPayload) => {
  const pdf = new jsPDF({ unit: "mm", format: "a4" });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  const bottomMargin = 22;
  const topMargin = 20;

  // Color palette (professional blue / gray / black)
  const colors = {
    navy: [22, 41, 71] as [number, number, number],
    accentBlue: [41, 98, 156] as [number, number, number],
    textDark: [25, 25, 28] as [number, number, number],
    textGray: [108, 114, 122] as [number, number, number],
    labelGray: [95, 100, 110] as [number, number, number],
    boxFill: [247, 249, 251] as [number, number, number],
    boxBorder: [223, 227, 233] as [number, number, number],
    hairline: [215, 219, 224] as [number, number, number],
  };

  let currentY = topMargin;
  let sectionIndex = 0;

  const checkPageBreak = (requiredSpace: number) => {
    if (currentY + requiredSpace > pageHeight - bottomMargin) {
      pdf.addPage();
      currentY = topMargin;
      return true;
    }
    return false;
  };

  // ---------- FOOTER ----------
  const addFooter = () => {
    const pageCount = pdf.getNumberOfPages();

    for (let page = 1; page <= pageCount; page++) {
      pdf.setPage(page);

      pdf.setDrawColor(...colors.hairline);
      pdf.setLineWidth(0.2);
      pdf.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);

      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(8.5);
      pdf.setTextColor(...colors.textGray);

      pdf.text(
        "Generated by Startup Application Portal",
        margin,
        pageHeight - 10
      );

      pdf.text(`Page ${page} of ${pageCount}`, pageWidth - margin, pageHeight - 10, {
        align: "right",
      });
    }
  };

  // ---------- HEADER (first page only) ----------
  const drawHeader = () => {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(20);
    pdf.setTextColor(...colors.navy);
    pdf.text("STARTUP APPLICATION", pageWidth / 2, currentY, { align: "center" });

    currentY += 6.5;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10.5);
    pdf.setTextColor(...colors.textGray);
    pdf.text("Startup Application Portal", pageWidth / 2, currentY, {
      align: "center",
    });

    currentY += 6;

    pdf.setDrawColor(...colors.accentBlue);
    pdf.setLineWidth(0.6);
    pdf.line(margin, currentY, pageWidth - margin, currentY);

    currentY += 10;
  };

  // ---------- SECTION TITLE ----------
  const sectionTitle = (title: string) => {
    sectionIndex += 1;
    checkPageBreak(14);

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(12.5);
    pdf.setTextColor(...colors.navy);
    pdf.text(`${sectionIndex}. ${title}`, margin, currentY);

    currentY += 2.5;
    pdf.setDrawColor(...colors.accentBlue);
    pdf.setLineWidth(0.4);
    pdf.line(margin, currentY, margin + 26, currentY);

    currentY += 7;
  };

  // ---------- FIELD GRID (grouped info card) ----------
  type Field = { label: string; value: string };

  const fieldGrid = (fields: Field[], columns: 1 | 2 = 2) => {
    const boxPadding = 6;
    const colGap = 8;
    const rowGap = 6;
    const labelValueGap = 4;
    const lineHeight = 5;

    const colWidth =
      columns === 2
        ? (contentWidth - boxPadding * 2 - colGap) / 2
        : contentWidth - boxPadding * 2;

    // group fields into rows
    const rows: Field[][] = [];
    for (let i = 0; i < fields.length; i += columns) {
      rows.push(fields.slice(i, i + columns));
    }

    // pre-compute wrapped lines + row heights
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10.5);

    const rowsWithLines = rows.map((row) =>
      row.map((field) => {
        const lines = pdf.splitTextToSize(field.value || "-", colWidth);
        return { ...field, lines };
      })
    );

    const rowHeights = rowsWithLines.map((row) => {
      const maxLines = Math.max(...row.map((f) => f.lines.length));
      return 4 + labelValueGap + maxLines * lineHeight;
    });

    const boxHeight =
      boxPadding * 2 +
      rowHeights.reduce((sum, h) => sum + h, 0) +
      rowGap * (rows.length - 1);

    // page break if box doesn't fit and isn't taller than a full page
    if (
      currentY + boxHeight > pageHeight - bottomMargin &&
      boxHeight < pageHeight - topMargin - bottomMargin
    ) {
      pdf.addPage();
      currentY = topMargin;
    }

    const boxTop = currentY;

    // draw box (card)
    pdf.setFillColor(...colors.boxFill);
    pdf.setDrawColor(...colors.boxBorder);
    pdf.setLineWidth(0.3);
    pdf.roundedRect(margin, boxTop, contentWidth, boxHeight, 2, 2, "FD");

    let rowY = boxTop + boxPadding;

    rowsWithLines.forEach((row, rowIdx) => {
      row.forEach((field, colIdx) => {
        const x = margin + boxPadding + colIdx * (colWidth + colGap);
        let fy = rowY;

        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(8);
        pdf.setTextColor(...colors.labelGray);
        pdf.text(field.label.toUpperCase(), x, fy);

        fy += labelValueGap;

        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(10.5);
        pdf.setTextColor(...colors.textDark);
        field.lines.forEach((line: string) => {
          pdf.text(line, x, fy);
          fy += lineHeight;
        });
      });

      rowY += rowHeights[rowIdx] + rowGap;
    });

    currentY = boxTop + boxHeight + 9;
  };

  // ---------- PARAGRAPH (description) ----------
  const paragraph = (text: string) => {
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10.5);
    pdf.setTextColor(...colors.textDark);

    const lines = pdf.splitTextToSize(text || "", contentWidth);
    const lineHeight = 5.6;

    lines.forEach((line: string) => {
      checkPageBreak(lineHeight);
      pdf.text(line, margin, currentY);
      currentY += lineHeight;
    });

    currentY += 6;
  };

  // ---------- NUMBERED LIST (team members) ----------
  const numberedList = (items: string[]) => {
    pdf.setFontSize(10.5);
    const lineHeight = 5.6;
    const numberColWidth = 10;

    items.forEach((item, index) => {
      const number = String(index + 1).padStart(2, "0");
      const lines = pdf.splitTextToSize(item, contentWidth - numberColWidth);

      checkPageBreak(lines.length * lineHeight + 2);

      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...colors.accentBlue);
      pdf.text(number, margin, currentY);

      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(...colors.textDark);

      lines.forEach((line: string, lineIdx: number) => {
        pdf.text(line, margin + numberColWidth, currentY + lineIdx * lineHeight);
      });

      currentY += lines.length * lineHeight + 3;
    });

    currentY += 3;
  };

  // ================= BUILD DOCUMENT =================

  drawHeader();

  // 1. APPLICANT INFORMATION
  sectionTitle("Applicant Information");
  fieldGrid([{ label: "Venture / Idea Name", value: application.idea }], 1);
  fieldGrid([
    { label: "Team Leader", value: application.leader },
    { label: "Email", value: application.email },
    { label: "Phone", value: application.phone },
    { label: "Department", value: application.department },
  ]);

  // 2. STARTUP INFORMATION
  sectionTitle("Startup Information");
  fieldGrid([
    { label: "Track", value: application.track },
    { label: "Sector", value: application.sector },
  ]);

  // 3. STARTUP DESCRIPTION
  sectionTitle("Startup Description");
  paragraph(application.description);

  // 4. TEAM MEMBERS
  sectionTitle("Team Members");
  numberedList(application.teams);

  addFooter();

  return pdf.output("blob");
};
const Stage2 = () => {
  const [track, setTrack] = useState("");
  const [sector, setSector] = useState("");
  const [otherSector, setOtherSector] = useState("");
  const [description, setDescription] = useState("");
  const [loading, setLoading] = useState(false);
  const [dis, setDis] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    const savedStage1 = localStorage.getItem("stage1");
    if (!savedStage1) {
      navigate("/");
    }
  }, [navigate]);

  const handleSumbit = async () => {
    const descriptionWordCount = description.trim().split(/\s+/).filter(Boolean).length;

    if (!track) {
      toast.error("Please select a track.");
      return;
    }

    if (!sector) {
      toast.error("Please select a sector.");
      return;
    }

    if (sector === "Other" && !otherSector.trim()) {
      toast.error("Please enter your sector.");
      return;
    }

    if (descriptionWordCount === 0) {
      toast.error("Please enter a startup description.");
      return;
    }

    if (descriptionWordCount > 150) {
      toast.error("Keep the startup description to 150 words or fewer.");
      return;
    }

    let stage1: Record<string, unknown>;
    try {
      stage1 = JSON.parse(localStorage.getItem("stage1") || "{}");
    } catch {
      toast.error("Your form session is invalid. Please fill Stage 1 again.");
      navigate("/");
      return;
    }

    const idea = typeof stage1.idea === "string" ? stage1.idea.trim() : "";
    const leader = typeof stage1.leader === "string" ? stage1.leader.trim() : "";
    const email = typeof stage1.email === "string" ? stage1.email.trim() : "";
    const phone = typeof stage1.phone === "string" ? stage1.phone.trim() : "";
    const department = typeof stage1.department === "string" ? stage1.department.trim() : "";
    const teams = Array.isArray(stage1.teams) ? stage1.teams.filter((t): t is string => typeof t === "string").map((t) => t.trim()) : [];

    if (!idea || !leader || !email || !phone || !department || teams.length === 0) {
      toast.error("Please complete Stage 1 before submitting.");
      navigate("/");
      return;
    }

    const application: ApplicationPayload = {
      idea,
      leader,
      email,
      phone,
      department,
      teams,
      track,
      sector: sector === "Other" ? otherSector : sector,
      description: description.trim(),
    };

    setLoading(true);
    setDis(true);

    // Parse the (possibly) unstructured description text and produce
    // a mapping from existing fields -> array of original description strings.
    const parseDescriptions = (text: string): Record<string, string[]> => {
      const snippets = text
        .split(/\n{2,}|\r\n{2,}/) // split on double newlines
        .map((s) => s.trim())
        .filter(Boolean);

      const mapping: Record<string, string[]> = {};
      const push = (key: string, val: string) => {
        if (!mapping[key]) mapping[key] = [];
        mapping[key].push(val);
      };

      const trackKeywords = [
        "Technology",
        "Sustainability",
        "Social",
        "FinTech",
        "HealthTech",
        "EdTech",
        "Consumer",
        "AgriTech",
        "Open Innovation",
      ];

      const sectorKeywords = [
        "Healthcare",
        "Education",
        "Agriculture",
        "E-commerce",
        "Finance",
        "Climate",
        "Artificial Intelligence",
        "Manufacturing",
        "Transportation",
        "Media",
        "Food",
        "Travel",
      ];

      const emailRegex = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i;
      const phoneRegex = /(?:\+?\d[\d\s().-]{5,}\d)/;

      for (const s of snippets) {
        // preserve original snippet exactly
        const original = s;

        // strong signals first
        if (emailRegex.test(s)) {
          push("email", original);
          continue;
        }

        if (phoneRegex.test(s)) {
          push("phone", original);
          continue;
        }

        // check for team lists (commas or lines of names)
        if (/\bteam\b/i.test(s) || /,/.test(s) && s.split(",").length >= 2) {
          push("teams", original);
          continue;
        }

        // leader name heuristics (short phrase with capitalized words)
        if (/^([A-Z][a-z]+\s?){1,3}$/.test(s)) {
          push("leader", original);
          continue;
        }

        // track keywords
        if (trackKeywords.some((k) => new RegExp(k, "i").test(s))) {
          push("track", original);
          continue;
        }

        // sector keywords
        if (sectorKeywords.some((k) => new RegExp(k, "i").test(s))) {
          push("sector", original);
          continue;
        }

        // short idea-like phrases
        if (s.length < 80 && /\b(app|platform|service|product|solution|system)\b/i.test(s)) {
          push("idea", original);
          continue;
        }

        // default: consider it a description candidate
        // but if we cannot confidently map, place under Unassigned
        // We'll use a conservative approach: place into `description` if it contains problem/impact keywords
        if (/\b(problem|solve|impact|market|users|customers|benefit|reduce|improve)\b/i.test(s)) {
          push("description", original);
          continue;
        }

        // fallback
        push("Unassigned", original);
      }

      return mapping;
    };

    const parsed = parseDescriptions(application.description);

    try {
      const pdfBlob = createApplicationPdf(application);
      const formData = new FormData();

      formData.append("idea", application.idea);
      formData.append("leader", application.leader);
      formData.append("email", application.email);
      formData.append("phone", application.phone);
      formData.append("department", application.department);
      formData.append("track", application.track);
      formData.append("sector", application.sector);
      formData.append("description", application.description);
      // Attach parsed descriptions JSON as an optional field. We do not
      // change existing field names; this is an additional optional payload
      // that the backend will ingest if present.
      try {
        formData.append("parsedDescriptions", JSON.stringify(parsed));
      } catch (e) {
        console.error("failed to attach parsedDescriptions", e);
      }

      application.teams.forEach((team) => formData.append("teams", team));
      formData.append("applicationPDF", new File([pdfBlob], "startup_application.pdf", { type: "application/pdf" }));

      const res = await fetch(`${apiBaseUrl}/application`, {
        method: "POST",
        body: formData,
      });

      const data = await res.json().catch(() => ({}));

      if (res.ok && data && data.success === true) {
        toast.success("Application submitted successfully and saved to Google Drive.");
        navigate("/submit");
      } else {
        const msg = (data && data.message) || `Application submission failed${res.status ? ` (status ${res.status})` : ""}`;
        toast.error(msg);
        return;
      }
    } catch (error) {
      console.error("SUBMIT ERROR:", error);
      toast.error("Unable to connect to server. Please try again.");
    } finally {
      setLoading(false);
      setDis(false);
    }
  };

  return (
    <div className="stage2-container">
      <div className="stage2-hero">
        <div>
          <p className="stage2-eyebrow">Step 2 of 2</p>
          <h2 className="stage-title">Startup Details</h2>
        </div>
        <div className="stage2-badge">Secure submission</div>
      </div>

      <div className="stage2-group">
        <label className="stage2-label">Track (Board)</label>

        <select
          className="stage2-select"
          value={track}
          onChange={(e) => setTrack(e.target.value)}
        >
          <option value="">Select Track</option>
          <option value="Technology & Innovation">Technology & Innovation</option>
          <option value="Sustainability & CleanTech">Sustainability & CleanTech</option>
          <option value="Social Impact">Social Impact</option>
          <option value="FinTech">FinTech</option>
          <option value="HealthTech">HealthTech</option>
          <option value="EdTech">EdTech</option>
          <option value="Consumer & D2C">Consumer & D2C</option>
          <option value="AgriTech">AgriTech</option>
          <option value="Open Innovation">Open Innovation</option>
        </select>
      </div>

      <div className="stage2-group">
        <label className="stage2-label">Sector</label>

        <select
          className="stage2-select"
          value={sector}
          onChange={(e) => setSector(e.target.value)}
        >
          <option value="">Select Sector</option>
          <option value="Healthcare">Healthcare</option>
          <option value="Education">Education</option>
          <option value="Agriculture">Agriculture</option>
          <option value="E-commerce / Retail">E-commerce / Retail</option>
          <option value="Finance & Banking">Finance & Banking</option>
          <option value="Climate & Environment">Climate & Environment</option>
          <option value="Artificial Intelligence / Deep Tech">Artificial Intelligence / Deep Tech</option>
          <option value="Manufacturing">Manufacturing</option>
          <option value="Transportation & Logistics">Transportation & Logistics</option>
          <option value="Media & Entertainment">Media & Entertainment</option>
          <option value="Food & Beverage">Food & Beverage</option>
          <option value="Travel & Hospitality">Travel & Hospitality</option>
          <option value="Other">Other</option>
        </select>

        {sector === "Other" && (
          <input
            className="stage2-input"
            type="text"
            placeholder="Enter your sector"
            value={otherSector}
            onChange={(e) => setOtherSector(e.target.value)}
          />
        )}
      </div>

      <div className="stage2-group">
        <label className="stage2-label" htmlFor="description">Startup description (up to 150 words)</label>
        <textarea
          id="description"
          className="stage2-input stage2-textarea"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Describe your startup idea, the problem it solves, and its impact."
          rows={7}
        />
        <span className="word-count">{description.trim().split(/\s+/).filter(Boolean).length} / 150 words</span>
      </div>

      <div className="stage2-buttons">
        <button className="back-btn" onClick={() => navigate("/")}>Back</button>
        <button disabled={dis} className="next-btn" onClick={handleSumbit}>{loading ? "Submitting..." : "Submit"}</button>
      </div>

    </div>
  );
};

export default Stage2;
